# Generated by Django 2.0.7 on 2019-07-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
