# Generated by Django 2.0.7 on 2019-07-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190725_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brandname',
            field=models.CharField(default=90, max_length=120),
            preserve_default=False,
        ),
    ]
